apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: blog-ghost
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

